#ifndef _DEFINE_H_
#define _DEFINE_H_
////////////////////////////////////////////////////////////////////////////////

//#define DEMO_CONFIG

//MAIN_WINDOW_SIZE
#define WINDOW_SIZE_WIDTH_NTSC 		704
#define WINDOW_SIZE_HEIGHT_NTSC		480
#define WINDOW_SIZE_WIDTH_PAL 		704
#define WINDOW_SIZE_HEIGHT_PAL		576

//DVR_TYPE
#define DVR_TYPE_CHANNEL_1		1
#define DVR_TYPE_CHANNEL_2		2
#define DVR_TYPE_CHANNEL_4		4
#define DVR_TYPE_CHANNEL_8		8

//INPUT_SIGNAL_TYPE
#define INPUT_NTSC				0
#define INPUT_PAL				1
#define INPUT_AUTODECT			2

//INPUT_CAMERA_SIGNAL_STATUS			
#define CAMERA_CHANNEL_1			0x0001
#define CAMERA_CHANNEL_2			0x0002
#define CAMERA_CHANNEL_3			0x0004
#define CAMERA_CHANNEL_4			0x0008
#define CAMERA_CHANNEL_5			0x0010
#define CAMERA_CHANNEL_6			0x0020
#define CAMERA_CHANNEL_7			0x0040
#define CAMERA_CHANNEL_8			0x0080

//RECORDING_CAMERA_SIGNAL_STATUS			
#define RECORDING_CHANNEL_1		0x0001
#define RECORDING_CHANNEL_2		0x0002
#define RECORDING_CHANNEL_3		0x0004
#define RECORDING_CHANNEL_4		0x0008
#define RECORDING_CHANNEL_5		0x0010
#define RECORDING_CHANNEL_6		0x0020
#define RECORDING_CHANNEL_7		0x0040
#define RECORDING_CHANNEL_8		0x0080


//ENCODE_VIDEO_CODEC_TYPE	
#define VIDEO_CODEC_H264_BASELINE	0
#define VIDEO_CODEC_H264_MAIN		1
#define VIDEO_CODEC_MPEG4		2
#define VIDEO_CODEC_MJPEG		3

//ENCODE_VIDEO_RESOLUTION
#define VIDEO_RES_360X240_NTSC		0		
#define VIDEO_RES_720X240_NTSC		1		
#define VIDEO_RES_720X480_NTSC		2		
#define VIDEO_RES_360X288_PAL		3		
#define VIDEO_RES_720X288_PAL		4		
#define VIDEO_RES_720X576_PAL		5		

//ENCODE_VIDEO_BITRATE
#define VIDEO_BITRATE_128KBPS		0
#define VIDEO_BITRATE_256KBPS		1
#define VIDEO_BITRATE_512KBPS		2
#define VIDEO_BITRATE_1MBPS		3
#define VIDEO_BITRATE_2MBPS		4
#define VIDEO_BITRATE_3MBPS		5
#define VIDEO_BITRATE_4MBPS		6
#define VIDEO_BITRATE_5MBPS		7
#define VIDEO_BITRATE_6MBPS		8


//#define MAX_AUDIOIN			8			

//ADUIO_CODEC_TYPE	
#define AUDIO_CODEC_G711			0
#define AUDIO_CODEC_G726			1

//AUDIO_SAMPLERATE
#define AUDIO_SAMPLERATE_8KHZ		0
#define AUDIO_SAMPLERATE_16KHZ		1
#if 0
//AUDIO_VOLUME
#define AUDIO_VOLUME_MIN			0
//#define AUDIO_VOLUME_MAX			15
//#define AUDIO_VOLUME_DEFAULT		8
#endif
#define AUDIOTYPE                       100
#define LIVE                            0
#define PLAYBACK                        1

//MOTION DETECTION
#define MOTION_MIN_SENSITIVITY		0
#define MOTION_MAX_SENSITIVITY		9

#define MOTION_BLOCK_W			22
#define MOTION_BLOCK_H			18

#define MOTION_MAX			(MOTION_BLOCK_W*MOTION_BLOCK_H)



//SENSOR_TYPE
#define SENSOR_TYPE_NO			0			
#define SENSOR_TYPE_NC			1			
#if 0
//SENSOR_STATUS			
//#define MAX_SENSOR				8
#define SENSOR_CHANNEL_1			0x0001
#define SENSOR_CHANNEL_2			0x0002
#define SENSOR_CHANNEL_3			0x0004
#define SENSOR_CHANNEL_4			0x0008
#define SENSOR_CHANNEL_5			0x0010
#define SENSOR_CHANNEL_6			0x0020
#define SENSOR_CHANNEL_7			0x0040
#define SENSOR_CHANNEL_8			0x0080
#endif
//ALARM_STATUS			
#define MAX_ALARM				4
#define ALARM_CHANNEL_1			0x0001
#define ALARM_CHANNEL_2			0x0002
#define ALARM_CHANNEL_3			0x0004
#define ALARM_CHANNEL_4			0x0008

#define ALARM_MIN_DELAY_SEC		1
#define ALARM_MAX_DELAY_SEC		30

//SPLASH
#define SPLASH_WINDOW_TIMER_COUNT  	10

//VIEW_MODE
#define VIEW_MODE_LIVE 			0	
#define VIEW_MODE_PLAYBACK 		1	

//SCREEN_MODE
#define SCREEN_MODE_1			1
#define SCREEN_MODE_4			4
#define SCREEN_MODE_8			8
#define SCREEN_MODE_9			9

#define SCREEN_MODE_MAX			9
#define MAX_CHANNEL			8			

#define MAX_CHAR				16
#define MAX_CWD				256

#define DEFAULT_SEQCOUNT			3


//PTZ INFO
#define INT_BAUDRATE_1200		0
#define INT_BAUDRATE_2400		1
#define INT_BAUDRATE_4800		2
#define INT_BAUDRATE_9600		3
#define INT_BAUDRATE_19200		4
#define INT_BAUDRATE_38400		5
#define INT_BAUDRATE_57600		6
#define INT_BAUDRATE_115200	7

#define INT_DATBIT_7			7
#define INT_DATBIT_8			8


#define INT_PARITY_NONE			0
#define INT_PARITY_ODD			1
#define INT_PARITY_EVEN	   	      2

#define INT_STOPBIT_1			1
#define INT_STOPBIT_2			2

//Internal PTZ List
#define PTZCTRL_DRX_500 			0
#define PTZCTRL_PELCO_D			1
#define PTZCTRL_PELCO_P              2

//Resolution
#define RESOLUTION_2CH_D1               0
#define RESOLUTION_4CH_CIF              1
#define RESOLUTION_8CH_CIF              2
#define RESOLUTION_4CH_D1				3
#define RESOLUTION_2CH_D1_PLUS_2CH_CIF	4	//2D1 REC/DEC  2CIF STREAMING
#define RESOLUTION_4CH_CIF_PLUS_D1		5
#define RESOLUTION_4D1_PLUS_4CIF_A		6	//4D1 REC/DEC  4CIF STREAMING
#define RESOLUTION_4D1_PLUS_4CIF_B		7	//4HD1 REC/DEC 4CIF STREAMING


//BITRATE_INDEX
#define BITRATE_IDX_64KBPS		0
#define BITRATE_IDX_128KBPS		1
#define BITRATE_IDX_256KBPS		2
#define BITRATE_IDX_512KBPS		3
#define BITRATE_IDX_1MBPS			4
#define BITRATE_IDX_2MBPS			5
#define	BITRATE_IDX_3MBPS			6
#define BITRATE_IDX_6MBPS			7

//BITRATE_ARANGE
#define BITRATE_ARG_HIGHEST		0
#define BITRATE_ARG_HIGH			1
#define BITRATE_ARG_MEDIUM		2
#define BITRATE_ARG_LOW				3

//BITRATE_TYPE

#define BITRATE_CBR			0
#define BITRATE_VBR			1

#if 0
// I FRAME INTERVAL
//#define IFRAME_INTERVAL_1			0
//#define IFRAME_INTERVAL_5			1
#define IFRAME_INTERVAL_10		2
//#define IFRAME_INTERVAL_15		3
//#define IFRAME_INTERVAL_30		4
#endif

// FRAME RATE
#define FRAMERATE_8		0
#define FRAMERATE_15	1
#define FRAMERATE_30	2

#if 0
// COLOR ADJUSTMENT
#define BRIGHTNESS_VALUE_MIN			0
#define BRIGHTNESS_VALUE_DEFAULT		100
#define BRIGHTNESS_VALUE_MAX			255

#define CONTRAST_VALUE_MIN			0
#define CONTRAST_VALUE_DEFAULT			100
#define CONTRAST_VALUE_MAX			255

#define SATURATION_VALUE_MIN			0
#define SATURATION_VALUE_DEFAULT		100
#define SATURATION_VALUE_MAX			255

#define HUE_VALUE_MIN				-180
#define HUE_VALUE_DEFAULT			0
#define HUE_VALUE_MAX				180
#endif
//EVENT
#define EVENT_REC_ONLY			0
#define EVENT_REC_MOTION		1
#define EVENT_REC_SENSOR		2
#define EVENT_REC_VIDEOLOSS		3
#define EVENT_REC_NORECORD		4
#define EVENT_REC_EMERGENCY		5

//RECORDING TYPE 
#define RECORDING_TYPE_RECYCLE		0
#define RECORDING_TYPE_ONCE		1

//IP TYPE
#define IP_STATIC 0
#define IP_DHCP 1

//CHIPSET TYPE//
#define DAVINCI_DM365	0
#define DAVINCI_DM368	1

//RUN_TIME SYSTEM MODE//
#define SYS_MODE_DVR	0
#define SYS_MODE_DVS	1

////////////////////////////////////////////////////////////////////////////////
#endif
